export const LINE_LEFT_POSITION = 28;
export const MARKER_SIZE = 8;
export const READING_CARD_HEIGHT = 20;
export const MARKER_LEFT_POSITION = LINE_LEFT_POSITION - MARKER_SIZE / 2;
export const READING_CARD_TEXT_LEFT_POSITION =
  LINE_LEFT_POSITION + MARKER_SIZE / 2;
